routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/about', 'PagesController@about');

/*
Route::get('/sendemail', function () {
  try {
    $result = "Your email has been sent successfully";
    $data = array(
      'name' => "Learning Laravel",
    );

    Mail::send('emails.learning', $data, function ($message) {
    $from = 'marina@marina.edufdezsoy.es';
    $name = 'Marina';
    $to = 'paco.portada@protonmail.com';
    $subject = "Learning Laravel test email";   

        $message->from($from, $name);
        $message->to($to);
        $message->subject($subject);
        });
    } catch (Exception $e) {
            $result = $e->getMessage();
    }

    return $result;
});

*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');







Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');




// Añado ---------------------------

// Quito ->  Route::get('/', 'PagesController@home');



Route::get('/', function () {
    return view('welcome');
});


Route::resource('reservas', 'ReservasController')->middleware('verified');


// Route::put('/reservas/{id}','ReservasController@update') -> name ('reservas.update');

// Route::resource('sites', 'SitesController')->middleware('verified');


 Route::get('reservas.search','ReservasController@search')  -> name('reservas.search');
 Route::get('reservas.searchdate','ReservasController@searchdate')  -> name('reservas.searchdate');
 Route::get('reservas.searchname','ReservasController@searchname')  -> name('reservas.searchname');

 Route::post('reservas.index2','ReservasController@index2')  -> name('reservas.index2');

 Route::post('reservas.index3','ReservasController@index3')  -> name('reservas.index3');

	 Route::get('reservas.index2','ReservasController@index2')  -> name('reservas.index2');

	 Route::get('reservas.index3','ReservasController@index3')  -> name('reservas.index3');


	 Route::post('reservas.indexsearchdate','ReservasController@indexsearchdate')  -> name('reservas/indexsearchdate');

	 Route::get('reservas.indexsearchdate','ReservasController@indexsearchdate')  -> name('reservas/indexsearchdate');

//Route::resource('sites', 'SitesController');

//Route::get('sites', 'SitesController@index');
//Route::get('sites/{site}', 'SitesController@show');
//Route::post('sites','SitesController@store');
//Route::put('sites/{site}','SitesController@update');
//Route::delete('sites/{site}', 'SitesController@delete');

resources/views/about.blade.php
<html>
    <head>
        <title>About Page</title>
        <link href='//fonts.googleapis.com/css?family=Lato:100' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 0;
                padding: 0;
                width: 100%;
                height: 100%;
                color: #B0BEC5;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }
            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }
            .content {
                text-align: center;
                display: inline-block;
            }
            .title {
                font-size: 96px;
                margin-bottom: 40px;
            }
            .quote {
                font-size: 24px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                <div class="title">About Page</div>
                <div class="quote">Our about page!</div>
            </div>
        </div>
    </body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">PADEL</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                <div class="content">
                    <div class="title m-b-md">
                        Marina Espinosa Gálvez - Ejercicio PADEL
                    </div>

                    <div class="links">
                        <a class="btn btn-info" href="{{ route('reservas.create') }}"> Añadir reserva</a> 
                       <a class="btn btn-info" href="{{ route('reservas.index') }}"> Ver y editar mis reservas</a> 
                       <a class="btn btn-success" href="{{ route('reservas.search') }}"> Buscar reservas por ID del usuario</a> 
                       <a class="btn btn-success" href="{{ route('reservas.searchname') }}"> Buscar reservas por nombre del usuario</a> 
                       <a class="btn btn-success" href="{{ route('reservas.searchdate') }}"> Buscar reservas en una fecha</a> 
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

                      {{-- <a class="btn btn-info" href="{{ route('reservas.search') }}"> Consultar reservas</a> --}}

resources/views/learning.blade.php
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8">
</head>
<body>
    <h2>Learning Laravel!</h2>
    <div>
        Welcome to {!! $name !!} website!
    </div>
</body>
</html>

resources/views/newsite.blade.php
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
    <title>Nueva reserva en la pista de padel</title>
</head>
<body>
    <p>Estos son los de su reserva creada a las {{ $reserva->created_at }}:</p>
    <ul>
        <li>Horas: {{ $reserva->numhoras }}</li>
        <li>Fecha: {{ $reserva->fecha }}</li>
    </ul>
</body>
</html>