routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/about', 'PagesController@about');

/*
Route::get('/sendemail', function () {
  try {
    $result = "Your email has been sent successfully";
    $data = array(
      'name' => "Learning Laravel",
    );

    Mail::send('emails.learning', $data, function ($message) {
    $from = 'marina@marina.edufdezsoy.es';
    $name = 'Marina';
    $to = 'paco.portada@protonmail.com';
    $subject = "Learning Laravel test email";   

        $message->from($from, $name);
        $message->to($to);
        $message->subject($subject);
        });
    } catch (Exception $e) {
            $result = $e->getMessage();
    }

    return $result;
});

*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');







Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');




// Añado ---------------------------

// Quito ->  Route::get('/', 'PagesController@home');



Route::get('/', function () {
    return view('welcome');
});


Route::resource('reservas', 'ReservasController')->middleware('verified');


// Route::put('/reservas/{id}','ReservasController@update') -> name ('reservas.update');

// Route::resource('sites', 'SitesController')->middleware('verified');


 Route::get('reservas.search','ReservasController@search')  -> name('reservas.search');
 Route::get('reservas.searchdate','ReservasController@searchdate')  -> name('reservas.searchdate');
 Route::get('reservas.searchname','ReservasController@searchname')  -> name('reservas.searchname');

 Route::post('reservas.index2','ReservasController@index2')  -> name('reservas.index2');

 Route::post('reservas.index3','ReservasController@index3')  -> name('reservas.index3');

	 Route::get('reservas.index2','ReservasController@index2')  -> name('reservas.index2');

	 Route::get('reservas.index3','ReservasController@index3')  -> name('reservas.index3');


	 Route::post('reservas.indexsearchdate','ReservasController@indexsearchdate')  -> name('reservas/indexsearchdate');

	 Route::get('reservas.indexsearchdate','ReservasController@indexsearchdate')  -> name('reservas/indexsearchdate');

//Route::resource('sites', 'SitesController');

//Route::get('sites', 'SitesController@index');
//Route::get('sites/{site}', 'SitesController@show');
//Route::post('sites','SitesController@store');
//Route::put('sites/{site}','SitesController@update');
//Route::delete('sites/{site}', 'SitesController@delete');

app/reservas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class reservas extends Model
{
    protected $fillable = ['numhoras', 'fecha', 'user_id', 'hora'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/ReservasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Illuminate\Support\Facades\Auth;
use App\Site;
use Exception;
use App\Mail\NewSiteEmail;
use Illuminate\Support\Facades\Mail;
use App\reservas;

class ReservasController extends Controller
{
	/**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {		
		$reservas = Auth::user()->reservas()->get();

        return view('reservas.index', compact('reservas'));
    }


	public function indexsearchdate(Request $request){
       $request->validate([
        'fecha'=> 'required|date|after:tomorrow|date_format:Y-m-d'
      ]);

	$reservas = DB::table('reservas')
                     ->select(DB::raw('*'))
                     ->where('fecha', '=', $request -> get('fecha'))
                     ->get();

		//$message;
		//$status;
		if (empty($reservas[0])){
			echo "Esta fecha no tiene reservas";
			//$status = "error";
			//$message = "Este usuario no existe o no tiene reservas añadidas aún";
		}

        return view('reservas.index2', compact('reservas')); //->with($status, $message);
	}

	public function index2(Request $request){

		$reservas = DB::table('reservas')
                     ->select(DB::raw('*'))
                     ->where('user_id', '=', $request -> get('iduser'))
                     ->get();

		//$message;
		//$status;
		if (empty($reservas[0])){
			echo "Este usuario no existe o no tiene reservas añadidas aún";
			//$status = "error";
			//$message = "Este usuario no existe o no tiene reservas añadidas aún";
		}

        return view('reservas.index2', compact('reservas')); //->with($status, $message);
	}

	public function index3(Request $request){
	$users = DB::table('users')
		               ->select('id') //  DB::raw('')
		               ->where('name', $request -> get('name'));

	$reservas = DB::table('reservas')
		    ->joinSub($users, 'users', function ($join) {
		        $join->on('users.id', '=', 'reservas.user_id');
		    })->get();


		if (empty($reservas[0])){
			echo "Este usuario no existe o no tiene reservas añadidas aún";
		}

        return view('reservas.index2', compact('reservas'));
	}

	public function search(){

        return view('reservas.search');
	}

	public function searchname(){
		 return view('reservas.searchname');
	}

	public function searchdate(){
		 return view('reservas.searchdate');
	}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('reservas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

       $request->validate([
        'numhoras'=>'required|max:2',
        'fecha'=> 'required|date|after:today|date_format:Y-m-d',
		'hora'=> 'required|date_format:H:i'
      ]);

$horatmp = $request->get('hora');
 $horatmp2 =  strtotime($horatmp) - 60*60;
$horatmp2 = date("h:i", $horatmp2);

 echo $horatmp;
 $horadespues =  strtotime($horatmp) + 60*60;

$horadespues = date("h:i", $horadespues);
echo $horadespues;
$fecha = $request->get('fecha');

	if ($request->get('numhoras') >= 1){
		$count = DB::select("select count(*) from reservas where fecha = '$fecha' and hora >= '$horatmp2' and hora < '$horadespues'");
print_r($count);

	if ($request->get('numhoras') == 2){
		 $horadespues =  strtotime($horatmp) + 60*60*2;
		$horadespues = date("h:i", $horadespues);
		$count = DB::select("select count(*) from reservas where fecha = '$fecha' and hora >= '$horatmp2' and hora < '$horadespues'");
	}

	$count = json_decode(json_encode($count), true);
		//$count = $count -> toArray();

echo $count[0]["count(*)"];
		if ($count[0]["count(*)"] == 0) { // -> "count(*)" > 0){
			echo "No solapa";
			  $reserva = new reservas([
				'numhoras' => $request->get('numhoras'),
				'fecha'=> $request->get('fecha'),
				'user_id' => Auth::id(),
				'hora'=> $request->get('hora')
			  ]);
			  $reserva->save();     
			  $status = "success";
			  $message = 'Una nueva reserva: ' . $reserva . ' se ha añadido';



			  $to = Auth::user()->email;
			  try {
				    Mail::to($to)->send(new NewSiteEmail($reserva));
				    $message = $message . " y el email se ha mandado";
			  } catch (Exception $exception) {
				  $status = "error";
				  $message = $message . ', pero no se ha enviado el email. Error: ' . $exception->getMessage();              
				}
		}
		else{
			$status = "error";
			$message = "En esta fecha y horas ya hay una reserva añadida";
		}
	}


	// if ($request->get('numhoras') >= 1)
	// select count(*) from reservas where fecha = $request->get('fecha'),
	// and hora >= $request->get('hora') and hora < strtotime('$request->get('hora')') + 60*60  ;

	// if $request->get('numhoras')== 2)
	// select count(*) from reservas where fecha = $request->get('fecha'),
	// and hora >= $request->get('hora') and hora < strtotime('$request->get('hora')') + 60*60*2  ;


/*
      $reserva = new reservas([
        'numhoras' => $request->get('numhoras'),
        'fecha'=> $request->get('fecha'),
        'user_id' => Auth::id(),
		'hora'=> $request->get('hora')
      ]);
      $reserva->save();     
      $status = "success";
      $message = 'Una nueva reserva: ' . $reserva . ' se ha añadido';



      $to = Auth::user()->email;
      try {
            Mail::to($to)->send(new NewSiteEmail($reserva));
            $message = $message . " y el email se ha mandado";
      } catch (Exception $exception) {
          $status = "error";
          $message = $message . ', pero no se ha enviado el email. Error: ' . $exception->getMessage();              
        }
*/
      return redirect('/reservas' )->with($status, $message);


	/**
	$numhoras = $request -> input('numhoras');	
	$fecha = $request -> input('fecha');
	$user_id = Auth::id();
	DB::insert('insert into reservas (numhoras, fecha) values (?, ?)', [$numhoras, $fecha]);
*/
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $reserva = reservas::findOrFail($id);
		echo $reserva -> id;

        return view('reservas.edit', compact('reserva'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

       $request->validate([
        'numhoras'=>'required|max:2',
        'fecha'=> 'required|date|after:today|date_format:Y-m-d',
		'hora'=> 'required|date_format:H:i'
      ]);

      $reserva = reservas::findOrFail($id);
      $reserva->fecha = $request->get('fecha');
	$reserva->hora = $request->get('hora');
      $reserva->numhoras = $request->get('numhoras');
      // $site->email = $request->get('email');


	$horatmp = $request->get('hora');
	 $horatmp2 =  strtotime($horatmp) - 60*60;
	$horatmp2 = date("h:i", $horatmp2);

	 echo $horatmp;
	 $horadespues =  strtotime($horatmp) + 60*60;

	$horadespues = date("h:i", $horadespues);
	echo $horadespues;
	$fecha = $request->get('fecha');

		if ($request->get('numhoras') >= 1){
			$count = DB::select("select count(*) from reservas where fecha = '$fecha' and hora >= '$horatmp2' and hora < '$horadespues'");
	print_r($count);

		if ($request->get('numhoras') == 2){
			 $horadespues =  strtotime($horatmp) + 60*60*2;
			$horadespues = date("h:i", $horadespues);
			$count = DB::select("select count(*) from reservas where fecha = '$fecha' and hora >= '$horatmp2' and hora < '$horadespues'");
		}

		$count = json_decode(json_encode($count), true);
			//$count = $count -> toArray();

	echo $count[0]["count(*)"];
			if ($count[0]["count(*)"] == 0) { // -> "count(*)" > 0){
				echo "No solapa";
					    $reserva->save();
			$status = "success";
			$message = 'La reserva ' . $reserva->id . ' se ha modificado';
			}
			else{
				$status = "error";
				$message = "En esta fecha y horas ya hay una reserva añadida";
			}
		}


      return redirect('/reservas')->with($status, $message);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
     $reserva = reservas::find($id);
     $temp = $reserva->id;
     $reserva->delete();

     return redirect('/reservas')->with('success', 'La reserva ' . $temp . ' se ha anulado correctamente');
    }
}

resources/views/reservas/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Añadir reserva
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('reservas.store') }}">
          <div class="form-group">
              @csrf
              <label for="numhoras">Número de horas:</label>
              <input type="number" min="1" max="2" class="form-control" name="numhoras" required/>
          </div>
          <div class="form-group">
              <label for="fecha">Fecha de la reserva:</label>
              <input type="date" min=<?php echo date('Y-m-d'); ?> max=<?php echo date('Y-m-d', strtotime("+1 week")); ?> class="form-control" name="fecha" required />
          </div>

			<div class="form-group">
			<label for="hora">Hora de la reserva</label>
			<input type="time" min=<?php echo "09:00:00";?> max=<?php echo "21:00:00";?> class="form-control" name="hora" required />
			</div>

          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email"/>
          </div>
          <button type="submit" class="btn btn-primary">Reservar</button>
          <a class="btn btn-secondary" href="{{ route('sites.index') }}"> Cancelar</a>
      </form>
  </div>
</div>
@endsection

resources/views/reservas/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Editar reserva
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif


 <form method="post" action="{{ route('reservas.update', $reserva->id) }}">
        @method('PUT')
        @csrf
          <div class="form-group">
              @csrf
              <label for="fecha">Número de horas de la reserva sin editar: {{ $reserva->numhoras}}</label>      <br/>      
              <label for="numhoras">Número de horas nuevo:</label>
              <input  type="number" min="1" max="2" class="form-control" name="numhoras" required value={{ $reserva->numhoras}}/>
          </div>
          <div class="form-group">

<!--
              <label for="fecha">Fecha de la reserva sin editar: {{ $reserva->fecha}}</label>      <br/>   
-->   
			  <label for="fecha">Fecha de la reserva:</label>
              <input type="date" min=<?php echo date('Y-m-d'); ?> max=<?php echo date('Y-m-d', strtotime("+1 week")); ?> class="form-control" name="fecha" required value={{ $reserva->fecha}} />
          </div>

<!--
              <label for="fecha">Hora de la reserva sin editar: {{ $reserva->hora}}</label>      <br/>   
-->
			<div class="form-group">
			<label for="hora">Hora de la reserva:</label>
			<input value={{ $reserva->hora}} type="time" min=<?php echo "09:00:00";?> max=<?php echo "21:00:00";?> class="form-control" name="hora" required />
			</div>


          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email" />
          </div>
          <button type="submit" class="btn btn-primary">Reservar</button>
          {{-- <a class="btn btn-secondary" href="{{ route('reservas') }}"> Cancelar</a> --}}
      </form>
  </div>
</div>
@endsection

resources/views/reservas/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Reservas </h2>
        </div>
        <div class="pull-right" align="right">
                <a class="btn btn-success mr-4 mb-2" href="{{ route('reservas.create') }}"> Nueva reserva </a>
        </div>
    </div>
</div>

<div class="uper">
  @if (session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  @if (session()->get('error'))
    <div class="alert alert-danger">
      {{ session()->get('error') }}  
    </div><br />
  @endif

  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Usuario</td>
          <td>Horas</td>
          <td>Fecha</td>
          <td>Hora</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($reservas as $reserva)
        <tr>
            <td>{{$reserva->id}}</td>
            <td>{{$reserva->user_id}}</td>
            <td>{{$reserva->numhoras}}</td>
            <td>{{$reserva->fecha}}</td>
            <td>{{$reserva->hora}}</td>

            <td><a href="{{ route('reservas.edit',$reserva->id)}}" class="btn btn-primary">Editar</a></td>
            <td>
                <form action="{{ route('reservas.destroy', $reserva->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>

        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection

resources/views/reservas/index2.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Reservas </h2>
        </div>
        <div class="pull-right" align="right">
                <a class="btn btn-success mr-4 mb-2" href="{{ route('reservas.create') }}"> Nueva reserva </a>
        </div>
    </div>
</div>

<div class="uper">
  @if (session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  @if (session()->get('error'))
    <div class="alert alert-danger">
      {{ session()->get('error') }}  
    </div><br />
  @endif

  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Usuario</td>
          <td>Horas</td>
          <td>Fecha</td>
          <td>Hora</td>

        </tr>
    </thead>
    <tbody>
        @foreach($reservas as $reserva)
        <tr>
            <td>{{$reserva->id}}</td>
            <td>{{$reserva->user_id}}</td>
            <td>{{$reserva->numhoras}}</td>
            <td>{{$reserva->fecha}}</td>
            <td>{{$reserva->hora}}</td>

        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection

resources/views/reservas/search.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Consultar reserva
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('reservas.index2') }}">
          <div class="form-group">
              @csrf
              <label for="iduser">ID del usuario:</label>
              <input type="number" class="form-control" name="iduser" required/>
          </div>
         
          <button type="submit" class="btn btn-primary">Buscar</button>
          
      </form>
  </div>
</div>
@endsection

resources/views/reservas/searchdate.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Consultar reserva
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('reservas/indexsearchdate') }}">
          <div class="form-group">
              @csrf
              <label for="iduser">Fecha de la reserva:</label>
              <input type="date" class="form-control" name="fecha" required/>
          </div>
         
          <button type="submit" class="btn btn-primary">Buscar</button>
          
      </form>
  </div>
</div>
@endsection

resources/views/reservas/searchname.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Consultar reserva
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('reservas.index3') }}">
          <div class="form-group">
              @csrf
              <label for="name">Nombre del usuario:</label>
              <input type="text" class="form-control" name="name" required/>
          </div>
         
          <button type="submit" class="btn btn-primary">Buscar</button>
          
      </form>
  </div>
</div>
@endsection